Run time fixes.

diff --git a/Scripts/shdel b/Scripts/shdel
--- a/Scripts/shdel
+++ b/Scripts/shdel
@@ -1,15 +1,9 @@
 #!/bin/bash -e
 
 usage() {
-    echo "Usage: shsub [-h]"
+    echo "Usage: shdel [-h] PID"
     echo ""
-    echo "Check the state of submitted jobs. Outputs one job per line."
-    echo "PID STATE"
-    echo "PID   : job process ID"
-    echo "STATE:"
-    echo " -1 : job is running"
-    echo " -2 : job exit code is missing"
-    echo " N  : job has finished with exit code N"
+    echo "Kill active job identified by a PID."
     echo ""
     echo "Opts:"
     echo " -h      : display this message"
@@ -34,6 +28,15 @@ do
     let N+=1
 done
 
+# Check for required args
+if [[ $# == 0 ]]
+then
+    echo Missing arguments ...
+    usage
+fi
+
+KILL_PID=$1
+
 # Job states are stored in DIR folder
 # The PIDs are stored in *.id files
 # The exit codes are stored in *.dat files
@@ -52,28 +55,24 @@ do
     # If no *.id files are found the ID is equal to PATTERN
     if [ "$ID" == "$PATTERN" ]
     then
-        exit 0
+        echo "Job $PID not found."
+        exit 1
     fi
 
     # Get the process pid and check that it is present in system proc table
     PID=$(cat $ID)
-    if [ -d /proc/$PID ]
+    if [[ $PID == $KILL_PID ]]
     then
-        # Process is running
-        echo "$PID -1"
-    else
-        # Check that .dat file exists
-        STATE=$(echo $ID | sed 's/\.id/\.dat/')
-        if [ -f $STATE ]
+        kill $KILL_PID
+        sleep 1
+        # If still running send KILL signal
+        if [ -d /proc/$PID ]
         then
-            # Return job exit state
-            echo "$PID $(cat $STATE)"
-        else
-            # No .dat file present - something went wrong
-            echo "$PID -2"
+            kill -9 $KILL_PID
         fi
-        # Remove info about finished processes
-        rm -f $ID
-        rm -f $STATE
+        exit 0
     fi
 done
+
+echo "Job $PID not found."
+exit 1
