Timing imvprovements / Daemon interface imvprovements.
- Daemon stop will not kill abruptly the server. An ALARM signal is
  issued and the server performs cleanup: db sync, thread joins.
- Introduced status command that will print overview of current jobs.
- Job start and terminate loops now have separate time counters and will
  interrupt when their time quota is exhausted. This allows the main
  loop to perform other tasks.

diff --git a/Scripts/shdel b/Scripts/shdel
--- a/Scripts/shdel
+++ b/Scripts/shdel
@@ -55,8 +55,8 @@ do
     # If no *.id files are found the ID is equal to PATTERN
     if [ "$ID" == "$PATTERN" ]
     then
-        echo "Job $PID not found."
-        exit 1
+        echo "No job info found."
+        exit 2
     fi
 
     # Get the process pid and check that it is present in system proc table
@@ -74,5 +74,5 @@ do
     fi
 done
 
-echo "Job $PID not found."
+echo "Job $KILL_PID not found."
 exit 1
